<?php

namespace App\Presenters;

use _PHPStan_76800bfb5\Nette\Neon\Exception;
use App\Forms\FormFactory;
use App\Forms\NewEmployeeFormFactory;
use App\Forms\EditEmployeeFormFactory;
use Kdyby\Translation\Translator;
use Nette\Security\IUserStorage;
use App\Model;

class MainPresenter extends BasePresenter
{
    public $sis;

    public $translator;
	private $newEmployeeFormFactory, $editEmployeeFormFactory, $formFactory, $lang,
        $userManager;

	public function __construct( NewEmployeeFormFactory $newEmployeeFormFactory, EditEmployeeFormFactory $editEmployeeFormFactory, FormFactory $formFactory,
                                Translator $translator, Model\UserManager $userManager)
	{
		$this->newEmployeeFormFactory = $newEmployeeFormFactory;
        $this->editEmployeeFormFactory = $editEmployeeFormFactory;
        $this->formFactory = $formFactory;
        $this->translator = $translator;
        $this->lang="cs";
        $this->userManager=$userManager;
        if(substr($_SERVER['REQUEST_URI'], 1, 2)=='en') {
            $this->lang="en";
        }

		parent::__construct();
	}

	protected function startup(): void
	{

        parent::startup();
	}

	public function beforeRender()
	{
		parent::beforeRender(); // TODO: Change the autogenerated stub
	}

	public function renderDefault()
	{
        $this->template->employees = $this->userManager->load_employees();
	    $this->template->lang="cs";
        if(substr($_SERVER['REQUEST_URI'], 1, 2)=='en') {
            $this->template->lang="en";
        }
	}

	protected function createComponentNewEmployeeForm()
	{
        return $this->newEmployeeFormFactory->create(function () {
            $this->flashMessage($this->translator->translate('website.main.successfully_added', NULL, [], NULL, $this->lang), 'alert alert-success');
            $this->redirect("Main:default");
        }, function ($e) {
            $this->flashMessage($e->getMessage(), 'alert alert-warning');
            $this->redirect('Main:default');
        });
	}
    protected function createComponentEditEmployeeForm()
    {
        return $this->editEmployeeFormFactory->create(function () {
            $this->flashMessage($this->translator->translate('website.main.successfully_edited', NULL, [], NULL, $this->lang), 'alert alert-success');
            $this->redirect("Main:default");
        }, function ($e) {
            $this->flashMessage($e->getMessage(), 'alert alert-warning');
            $this->redirect('Main:default');
        });
    }

}
